rescript-lang/rescript-editor-support

src/rescript-editor-support/EditorSupportCommands.re
=> Use appropriate output channel

src/rescript-editor-support/Hover.re
This make it possible for clients to use correct syntax highlighting in hovers.
Vim example:
=> Support syntax highlight in hover fenced blocks

src/rescript-editor-support/EditorSupportCommands.re, src/rescript-editor-support/Pretty.ml, src/rescript-editor-support/Pretty.mli, src/rescript-editor-support/RescriptEditorSupport.re, src/rescript-editor-support/vendor/omd/omd_parser.ml
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/19
Suppress all printing to stdout.
Print `[]` in case of internal error. For examople, if the project was never built, or a file cannot be built for the first time because of syntax errors. In that case, there's an internal error as the `.cmt` cannot be found.
=> Always output valid json, even in case of internal error.

editor-extensions/vscode/package.json, editor-extensions/vscode/src/index.js, src/ppx/Ppx_Monads.re, src/rescript-editor-support/EditorSupportCommands.re, src/rescript-editor-support/Files.re, src/rescript-editor-support/FindFiles.re, src/rescript-editor-support/Infix.re, src/rescript-editor-support/MessageHandlers.re, src/rescript-editor-support/Monads.re, src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/Packages.re, src/rescript-editor-support/ProcessExtra.re, src/rescript-editor-support/Query.re, src/rescript-editor-support/References.re, src/rescript-editor-support/State.re, src/rescript-editor-support/dune, src/rescript-editor-support/vendor/omd/omd.ml, src/rescript-editor-support/vendor/omd/omd.mli, src/rescript-editor-support/vendor/omd/omd_lexer.ml, src/rescript-editor-support/vendor/omd/omd_lexer.mli
Reduce size of binaries. E.g from 16MB to 8MB on macos.
=> Reduce dependencies

Changes.md, src/rescript-editor-support/Log.re, src/rescript-editor-support/RescriptEditorSupport.re
Fixes https://github.com/rescript-lang/rescript-vscode/issues/47.
=> Don't create a log file by default.

Changes.md, examples/example-project/src/ZZ.res, src/rescript-editor-support/Hover.re, src/rescript-editor-support/References.re
Fixes https://github.com/rescript-lang/rescript-vscode/issues/52
Continuation of https://github.com/rescript-lang/rescript-editor-support/pull/47
Show the correct type information, including type definition for record fields.
Also, fix issue in the docstring shown. Before it was either misssing (entire record type) or wrong (for record field, it was showing the doc comment of the containing record type).
Clean up code in References.
=> Fix hovering on record fields.

Changes.md, examples/example-project/src/ModuleWithDocComment.res, examples/example-project/src/ZZ.res, src/rescript-editor-support/Hover.re, src/rescript-editor-support/ProcessCmt.re, src/rescript-editor-support/SharedTypes.re
Fixes https://github.com/rescript-lang/rescript-vscode/issues/58
=> Add support for doc strings when hovering on modules.

Changes.md, src/rescript-editor-support/PartialParser.re
The backwards partial parser used by autocomplete can go into an infinite loop.
Repro: file `" }` then edit adding `.`.
Could be the cause of https://github.com/rescript-lang/rescript-vscode/issues/43
=> Fix infinite loop in autocomplete.

Changes.md, examples/example-project/src/ZZ.res, src/rescript-editor-support/ProcessExtra.re
Fix cross-reference for type definitions belonging to an inner module. The lookup used to search values instead of types.
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/54
=> Fix jump to type definition for types defined in an inner module.

src/rescript-editor-support/Hover.re, src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/PartialParser.re, src/rescript-editor-support/ProcessExtra.re, src/rescript-editor-support/Query.re, src/rescript-editor-support/References.re, src/rescript-editor-support/RescriptEditorSupport.re
`x->` where `x` is a variable name of known type defined inside a module. E.g. `Belt.List.t`.
=> Explore autocomplete for pipe-first.

Changes.md, examples/example-project/src/ZZ.res, src/rescript-editor-support/ProcessCmt.re
This happens when a value is definied multiple times inside an inner module. E.g. @react.component defines `make` twice.
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/67
=> Fix hover on definitions inside a react component module.

Changes.md, examples/example-project/src/ZZ.res, src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/NotificationHandlers.re, src/rescript-editor-support/PartialParser.re, src/rescript-editor-support/RescriptEditorSupport.re
Given a context `foo(... ~lab)`, parse backwards to find `foo`, get the type and list of labels, and complete from `lab`.
Fix https://github.com/rescript-lang/rescript-vscode/issues/65.
=> Add support for autocomplete of labelled arguments.

Changes.md, src/rescript-editor-support/NewCompletions.re
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/72
=> Fix priority in multiple opens.

Changes.md, editor-extensions/vscode/package-lock.json, editor-extensions/vscode/package.json, examples/example-project/src/ZZ.res, src/rescript-editor-support/Hover.re, src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/ProcessAttributes.re, src/rescript-editor-support/ProcessCmt.re, src/rescript-editor-support/References.re, src/rescript-editor-support/SharedTypes.re
Add support for `@deprecated` attributes in autocomplete and hover.
For autocomplete: tell the client that the item is deprecated (typically shown with a strike-through by the client). Also, show the deprecation message.
For hover, show the deprecation message.
See https://github.com/rescript-lang/rescript-vscode/issues/45
=> Add support for @deprecated attributes in autocomplete and hover.

Changes.md, src/rescript-editor-support/BuildSystem.re
Look for `rescript` in addition to `bs-platform` in `node_modules`.
=> Support for upcoming `rescript` npm package for the compiler.

Changes.md, src/rescript-editor-support/PartialParser.re
Normal case:
- `open! M`
Some corner cases:
- `open  !  M`
- `open!M`
=> Autocomplete: add support for `open!` in addition to `open`.

Changes.md, src/rescript-editor-support/Uri2.re
Fixes https://github.com/rescript-lang/rescript-vscode/issues/98#L345
The issue arises when the drive letter is lowercase.
=> Fix issue in jump-to-definition on Windows.

.gitignore, src/ppx2/Ppx_Unmonads.re, src/ppx2/dune, unmonad.sh
- The let%try and others ended up swallowing lots of important production errors (surprise... =/)
- The transforms in their current state don't give an error message location (partially due to usage of metaquot. Meta yak shaving).
- This makes the build depend on OMP, ppxlib and others. Giant deps, giant build times.
- But seriously, if even Cristiano has problem writing proper option and result handling in production because of `let%` stuff then what chance do most others have.
Anyway I'm gonna remove it because this seems to be a blocker for cleaning up the codebase's other parts...
First step is to build the same monad ppx as an executable; I'll directly run this through the source files using `unmonad.sh`, print them back to Reason syntax, and manually clean up some stuff.
See #86, …
=> Start removing let%foo

src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/PartialParser.re
Autocomplete for JSX props is only distinguished from autocomplete for identifiers by the context in which it takes place. Compared to completion of labeled arguments, it is not triggered by any special characters such as `~`.
The context is used as a heuristic to interpret the **intention**.
So for example, this should complete `foo` as a prop from `Comp`:
```rescript
<Comp foo
```
so should this
```rescript
<Comp x=3 foo
```
but this should complete as an identifier:
```rescript
<Comp x=foo
```
this should also complete as an identifier:
```rescript
<Comp List.m
```
as even though it's in a place where a prop name is expected, the intent is clearly to complete a value from module `List`.
This is a WIP to define what the contexts are.
=> WIP ground work for future autocomplete for JSX props.

src/ppx2/Ppx_Unmonads.re, src/rescript-editor-support/BuildSystem.re, src/rescript-editor-support/FindFiles.re
Follow-up of #87
Now we can properly add error handling to these `None`/`Error(_)` later
=> Make the unmonad script turn the let% into `switch` instead

src/rescript-editor-support/Hover.re, src/rescript-editor-support/MessageHandlers.re, src/rescript-editor-support/NewCompletions.re, src/rescript-editor-support/NotificationHandlers.re, src/rescript-editor-support/Packages.re, src/rescript-editor-support/ProcessExtra.re, src/rescript-editor-support/Process_406.re, src/rescript-editor-support/Protocol.re, src/rescript-editor-support/Query.re, src/rescript-editor-support/References.re, src/rescript-editor-support/RescriptEditorSupport.re, src/rescript-editor-support/State.re
- Convert Hover to unmonad
- Convert MessengerHandlers to unmonad
- Convert NotificationHandlers to unmonad
- Convert Packages to unmonad
- Convert Process_406 to unmonad
- Convert ProcessExtra to unmonad
- Convert Protocol to unmonad
- Convert NewCompletions to unmonad
- Convert Query to unmonad
- Convert References to unmonad
- Convert RescriptEditorSupport.re to unmonad
- Convert State over to unmonad
@cristianoc I've made a commit per file and will do a rebase merge instead of the usual squash merge, so that you can bisect in case some conversion went wrong.
This diff should be read with whitespace sensitivity turned off. The option is in the diff view
=> Convert everything over to unmonad

Changes.md, src/PartialParser.ml
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/99
=> Autocomplete fix: don't let `->` override `.` autocomplete

Changes.md, examples/example-project/src/ZZ.res, src/NewCompletions.ml, src/PartialParser.ml
Use a dedicated code path that takes care of pipe and is separate from normal identifiers.
=> Improve code for pipe autocomplete.

src/EditorSupportCommands.ml, src/RescriptEditorSupport.ml
The only user of the binary is the editor plugin; we don't have to parse
Less parsing is good for whitespace management too.
Will need to update the editor plugin later.
=> New `complete` CLI api without parsing file:line:char

src/EditorSupportCommands.ml, src/Protocol.ml, src/RescriptEditorSupport.ml
This directly returns the right lsp hover payload.
I've modified it from the dump logic, which might still be wanted for testing or such. So this PR might not be merge friendly yet. But I wanna have some feedback first. If we're keeping dump, then I'll modify this diff to add the extra `hover` function instead of overriding dump.
=> Clean up hover code

src/EditorSupportCommands.ml, src/Protocol.ml, src/RescriptEditorSupport.ml, src/Utils.ml
=> Split definition into a dedicated api

src/FindFiles.ml, src/MarkdownOfOCamldoc.ml, src/Packages.ml, src/PartialParser.ml, src/PrepareUtils.ml, src/Utils.ml
=> Remove most Str.split

Changes.md, src/References.ml, src/SharedTypes.ml, src/Utils.ml, test/src/Hover.res, test/src/expected/Hover.res.txt
Fixes https://github.com/rescript-lang/rescript-editor-support/issues/132.
=> Fix hover on labels with type annotation in components.

.depend, .gitignore, Makefile, lib/README.md
We need to make this repo embeddable in others, and we have a few makefile-related workflows to share, so here we are.
Pros:
- No dep on dune. There's been a few install-time conflicts in the past. Dune also isn't small.
- Easier embedding.
- Simpler setup. Entropy--
- Easier integration with tests.
Cons:
- Less convenient than dune at times. Now we're maintaining a makefile.
- Dune does incrementalism a better than makefiles.
Build speed is around the same.
=> Try using makefile
